# nixpacks.toml

[phases.setup]
nixPkgs = ["curl", "bash", "python311"]

[phases.install]
cmds = [
    # 1. Create the Python virtual environment
    "python3.11 -m venv /opt/venv",

    # 2. Upgrade pip and install all our Python packages
    "/opt/venv/bin/pip install --upgrade pip",
    "/opt/venv/bin/pip install --no-cache-dir -r requirements.txt",
    
    # 3. Install Ollama with retry logic
    "for i in 1 2 3; do curl -fsSL https://ollama.com/install.sh | sh && break || sleep 10; done",
    
    # 4. Generate the vector database (do this during build to save startup time)
    "echo 'Generating vector DB... this happens once during build'",
    "/opt/venv/bin/python prepare_data.py"
]

[start]
cmd = "bash start.sh"