[phases.setup]
nixPkgs = ["curl", "bash"]

[phases.install]
cmds = [
    # Use the full path to pip to avoid "command not found"
    "/opt/venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "bash start.sh"