# nixpacks.toml

[phases.setup]
# We're telling Nixpacks we need curl, bash, and python3.9
nixPkgs = ["curl", "bash", "python39"]

[phases.install]
cmds = [
    # 1. Create the Python virtual environment
    "python3.9 -m venv /opt/venv",
    
    # 2. Install all our Python packages
    "/opt/venv/bin/pip install -r requirements.txt",
    
    # --- One-Time Build Tasks ---
    # These run only when Railway builds the image
    
    # 3. Install Ollama
    "curl -fsSL https://ollama.com/install.sh | sh",
    
    # 4. Pull the smaller, faster phi model
    "echo 'Pulling phi... this happens once during build'",
    "ollama pull phi",
    
    # 5. Generate the vector database
    "echo 'Generating vector DB... this also happens once during build'",
    "/opt/venv/bin/python prepare_data.py"
]

[start]
# This just tells Nixpacks what command to run at startup
cmd = "bash start.sh"